FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /DigitalStoreAPI

# #Change the images current working directory
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /DigitalStoreAPI
EXPOSE 80
COPY  --from=build-env /DigitalStoreAPI/out .

ENTRYPOINT ["dotnet", "DigitalStoreAPI.dll"]